### ISSUE TITLE
Vec Test Failing

### ISSUE THREAD

**Issue by rbales-usgs** [USGS-CMG/stglib#226]
For some reason the vector test is failing for me. Steve is also having the same issue. We both are getting this error when the test runs `vec_wvs("NBMCSBvec01-a.nc")`:

`FAILED stglib/tests/test_scripts.py::test_vec - FileNotFoundError: [WinError 2] The system cannot find the file specified`

I checked the tests/data folder and NBMCSBvec01-a.nc is in there. Next, I tried to manually run `runvecnc2waves.py` with that netcdf file but also having issues getting it to work. Now, I get the error `'runvecnc2waves.py' is not recognized as an internal or external command,
operable program or batch file`. 

Do you know why this may be happening?

**Comment by dnowacki-usgs** [comment]
Hi Bo--this is puzzling, because the automated tests running on Windows on GitHub actions are working. I suspect this may be an installation issue but it's strange that you both are encountering problems. Maybe try running `pip install -e . --no-deps`, which should remove and re-install stglib. Check the installation docs for more details.

**Comment by rbales-usgs** [comment]
That worked, thank you!
