### ISSUE TITLE
eofe code bug

### ISSUE THREAD

**Issue by rbales-usgs** [USGS-CMG/stglib#252]
Could not process altimeter data (instrument type: aa) due to an index error raised when running def load_aa_point. After looking into it, it's failing because there is some trailing information following the data in the .log file. Most of this trailing information is repeated from the header details at the start of the .log file. 

We don't really need any of these trailing details, and what is handy is already grabbed and added to the global attributes earlier in the code. Instead of manually removing this data I wrote a line that will cut out the unnecessary lines after the data. Will send in a PR today.

**Comment by ssuttles-usgs** [comment]
[like]  Suttles, Steven E reacted to your message:
________________________________
From: rbales-usgs ***@***.***>
Sent: Thursday, August 15, 2024 12:24:15 PM
To: USGS-CMG/stglib ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [USGS-CMG/stglib] eofe code bug (Issue #252)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Could not process altimeter data (instrument type: aa) due to an index error raised when running def load_aa_point. After looking into it, it's failing because there is some trailing information following the data in the .log file. Most of this trailing information is repeated from the header details at the start of the .log file.

We don't really need any of these trailing details, and what is handy is already grabbed and added to the global attributes earlier in the code. Instead of manually removing this data I wrote a line that will cut out the unnecessary lines after the data. Will send in a PR today.

**Comment by dnowacki-usgs** [comment]
Closed by #253.
