### ISSUE TITLE
encoding not a keyword in xr.DataArray

### ISSUE THREAD

**Issue by sccrosby** [USGS-CMG/stglib#59]
Line 145 of rsk2cdf.py encountering an error, encoding not a valid keyword.

    if ("instrument_type" in ds.attrs) and (ds.attrs["instrument_type"] == "rbr_duo"):
        ds["T_28"] = xr.DataArray(
            t["temp"],
            coords=[times, samples],
            dims=("time", "sample"),
            name="Temperature",
            attrs={
                "units": "C",
                "long_name": "Temperature",
                "epic_code": 28,
                "serial_number": ds.attrs["serial_number"],
            },
            encoding={"_FillValue": 1e35},
        )

**Comment by sccrosby** [comment]
This appears to fix.

    # If duo, also save temp
    if ("instrument_type" in ds.attrs) and (ds.attrs["instrument_type"] == "rbr_duo"):
        ds["T_28"] = xr.DataArray(
            t["temp"],
            coords=[times, samples],
            dims=("time", "sample"),
            name="Temperature",
            attrs={
                "units": "C",
                "long_name": "Temperature",
                "epic_code": 28,
                "serial_number": ds.attrs["serial_number"],
            }
            #encoding={"_FillValue": 1e35},
        )
        ds["T_28"].encoding = {"_FillValue": 1e35}

**Comment by dnowacki-usgs** [comment]
Interesting. The 1e35 fill value is a holdover from the EPIC days for systems that could not handle NaN. I think we should remove that altogether for this code as we are publishing all CF from now on. Thoughts?

**Comment by sccrosby** [comment]
Oh yea, that sounds good to me. This library has changed a bit since I last
used it, need to figure out this tag for CF. that's a nice update.

**Comment by ssuttles-usgs** [comment]
While true that we can do CF only data releases now, EPIC is still allowed. Maybe should wait to remove the functionality?

-steve


Steven Suttles
U. S. Geological Survey, Woods Hole Coastal and Marine Science Center
384 Woods Hole Road, Woods Hole, MA 02543-1598
***@***.******@***.***>
(508) 457-2228 (o)
(410) 200-0734 (c)
________________________________
From: Dan Nowacki ***@***.***>
Sent: Wednesday, November 17, 2021 5:28 PM
To: USGS-CMG/stglib ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] Re: [USGS-CMG/stglib] encoding not a keyword in xr.DataArray (Issue #59)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Interesting. The 1e35 fill value is a holdover from the EPIC days for systems that could not handle NaN. I think we should remove that altogether for this code as we are publishing all CF from now on. Thoughts?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUSGS-CMG%2Fstglib%2Fissues%2F59%23issuecomment-972159523&data=04%7C01%7Cssuttles%40usgs.gov%7Ca9d06a677c744bb7ead208d9aa19a173%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637727849332279529%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Nlsr9zrF9XWiy%2B4VJkAfpuhuzuATdczXTQ3vYoA03GM%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJEPJ2EZLHJLIMAKR4HDLT3UMQUA5ANCNFSM5IIECYSQ&data=04%7C01%7Cssuttles%40usgs.gov%7Ca9d06a677c744bb7ead208d9aa19a173%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637727849332289488%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=E84ACsj2V%2F1MZugmNgrQjEPKeYvG8VuBgV%2FDpazDF8Y%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cssuttles%40usgs.gov%7Ca9d06a677c744bb7ead208d9aa19a173%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637727849332289488%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=fOHYgzwm3t3H3Ike%2BOabb2twHsyNU9zxBCcdl5Ea%2B%2B8%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cssuttles%40usgs.gov%7Ca9d06a677c744bb7ead208d9aa19a173%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637727849332299446%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=glwUDLqcpKdDuAW6DlZwSu9Kfrdkp84pxIc9rPDCmf4%3D&reserved=0>.
